#! /bin/bash
# .bashplug

VERSION=0.13

[[ $- != *i* ]] && return
# case?
if   [ "$UID" == "0" ];    then PS1="  \033[00;31m\u@\h \033[01;34m\w # \033[00m";
elif [ $UID -eq 1001 ];    then PS1="  \033[00;33m\u@\h \033[01;35m\w # \033[00m";
else                            PS1="  \033[00;32m\u@\h \033[01;34m\w $ \033[00m"; fi

set -o nounset

PATH=$PATH:.:~/.bashplug

export GREP_COLOR="1;35"
export HISTCONTROL=ignoreboth          # ignoredups & ignorespace
shopt -s histappend                    # append to the history file, don't overwrite it
shopt -s checkwinsize                  # update window size after each cmd (if necessary)

if [ -d ~/.bashplug ]
then
  source ~/.bashplug/control
  source ~/.bashplug/functions
  source ~/.bashplug/aliases
  source ~/.bashplug/git
  source ~/.bashplug/stats
  #version
else
  echo "~/.bashplug not present"
fi
