#! /bin/bash
# .bashplug

BASHPLUG_VERSION=0.12

[[ $- != *i* ]] && return
if [ "$UID" == "0" ]; then PS1="  \033[00;31m\u@\h \033[01;34m\w # \033[00m"; 
else                       PS1="  \033[00;32m\u@\h \033[01;34m\w $ \033[00m"; fi

PATH=$PATH:.:~/.bashplug

export GREP_COLOR="1;31"
export HISTCONTROL=ignoreboth          # ignoredups & ignorespace
shopt -s histappend                    # append to the history file, don't overwrite it
shopt -s checkwinsize                  # update window size after each cmd (if necessary)

if [ -d ~/.bashplug ]
then
  source ~/.bashplug/control
  source ~/.bashplug/aliases
  source ~/.bashplug/git

  prnt_summ "bashplug files sourced: version $BASHPLUG_VERSION"
else
  echo "~/.bashplug not present"
fi

# information to print on login:

prnt_info "now logged in:"
last | grep still

prnt_info "previous users logged in:"
prnt_summ " - - to do - - "
uptime

